### ISSUE TITLE
Program doesn't close all the way using stop command

### ISSUE THREAD

**Issue by tomrhollis** [clarkx86/vellum#13]
A very minor issue but it could mess with batch scripts.

OS: Windows
To reproduce:
1) Execute vellum
2) Wait for BDS to finish loading
3) type "stop"
4) Sticks on "vellum quit correctly" until user hits enter

If you type a command instead of enter, it throws an exception instead.

Can be fixed with one line, but not sure if/how it would affect Linux. See upcoming pull request. #14

**Comment by clarkx86** [comment]
Hey! Thanks a lot for reporting this issue and for your PR :slightly_smiling_face:!
I just merged it into the `development` branch because I will work my way through the remaining pull requests today, and then merge everything into master and push a new release :slightly_smiling_face:!

I remember also stumbling across this issue and thinking that probably there is also a "*cleaner*" way of exiting vellum instead of calling `System.Environment.Exit(0);` because if all resources are freed and the application reaches the end of the call stack, it should just quit, which let's me to believe there is probably still some thread(s) running when executing the `stop` command (probably the `backupIntervalTimer` and `renderIntervalTimer` timers?). But anyway, this will do for now and once again thank you very much for your pull request :slightly_smiling_face:.

**Comment by tomrhollis** [comment]
Thanks for the merge, it was a simple little thing but any GitHub activity
will help while I'm trying to break into the development scene fresh out of
school in these interesting times.

If the new release doesn't resolve the notify before backup issue I'll take
a look at that next because I'm also experiencing that.

Otherwise I'm planning to make ElementZero discord integration using the
fact that EZ copies chat to stdout and vellum is already watching stdout.
That probably wouldn't go well in the main code since most people don't use
EZ, but if you're ok with it I'd have it up on my fork for others with EZ
and keep merging in your upstream changes. Or I could keep it to myself,
let me know what you think is best for the project

Tom
(Rowlga on the discord)

**Comment by clarkx86** [comment]
Fixed with https://github.com/clarkx86/vellum/commit/76ea401e970ca64856dd8e90751f566a240c5cc3
