### ISSUE TITLE
Hot buckup?

### ISSUE THREAD

**Issue by Dardle** [clarkx86/vellum#36]
What is the difference between a backup without a server stop and a backup with With backup from Server stop

**Comment by clarkx86** [comment]
The backed up files (or better said the backup-archive) will be the same using either method, the only difference is that with hot-backups, a server doesn't have to be stopped while performing a backup. Hot-backups are probably the preferred method most people would want to use, while non-hot-backups (with restarts) were basically used for Windows servers because hot-backups were only possible on Linux (which has been fixed now).
