### ISSUE TITLE
On windows, with 1.16 BDS, hot backups should work right?

### ISSUE THREAD

**Issue by voult2** [clarkx86/vellum#5]
However, the executable is terminating with this error:  

"NOTICE: Hot-backups are currently not supported on Windows. Please enable "StopBeforeBackup" in the "configuration.json" instead."  

There was known bug with 1.14 that prevent Hot-Backups. With 1.16 maybe it got fixed?

**Comment by clarkx86** [comment]
I know we already talked about this issue on Discord @voult2, but I'm going to clarify it here on GitHub as well for others who might be interested :).

Unfortunately taking hot backups using the `save hold` command *seems* to not be working on Windows due to file access permissions, on Linux it does though. We *may* just be doing something wrong however (anyone how is on to something or has a workaround: feel free to file a pull request!). But as far as I know it's a common issue which has already been reported on the BDS JIRA [here](https://bugs.mojang.com/browse/BDS-2733).

I'm going to leave this open so we can discuss on the progress of this issue :).

**Comment by clarkx86** [comment]
Hot-backups on Windows are now enabled with commit https://github.com/clarkx86/vellum/commit/76ea401e970ca64856dd8e90751f566a240c5cc3.
